### ISSUE TITLE
ipc.Msgctl can not use

### ISSUE THREAD

**Issue by flyhope** [siadat/ipc#6]
I want to get stat, but no any function can use.

this code can't return any data.

```
ipc.Msgctl(qid, ipc.IPC_STAT)
```

**Comment by siadat** [comment]
You are right. Thank you for opening the this issue. The FIXME comment for
it is in
https://github.com/siadat/ipc/blob/aa64281dea7a8ad73f77aed5c0b81bcc23a8333a/msgctl.go#L8

We need to implement the msgid_ds struct as described in
http://man7.org/linux/man-pages/man2/msgctl.2.html and write a few tests
that uses it.

At the moment, I am not able to work for a few days, due to being sick. If
you are in a hurry feel free to write the struct and test it yourself and
send me a pull-request. Otherwise, I will do my best to work on it as soon
as I can. Apologies for the inconvenience.
